---
apiVersion: v1
kind: Namespace
metadata:
  name: instorage-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: instorage-manager
  namespace: instorage-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: instorage-manager
  namespace: management-controller
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: instorage-manager-crb
subjects:
- kind: ServiceAccount
  name: instorage-manager
  namespace: management-controller
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: instorage-manager
  namespace: instorage-system
  labels:
    app: instorage-manager
spec:
  selector:
    matchLabels:
      app: instorage-manager
  template:
    metadata:
      labels:
        app: instorage-manager
    spec:
      serviceAccountName: instorage-manager
      nodeSelector:
        csd.enabled: "true"
      containers:
      - name: manager
        image: ketidevit2/instorage-manager:v0.0.1
        imagePullPolicy: IfNotPresent
        args:
        - --grpc-port=50051
        - --zap-log-level=info
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - name: grpc
          containerPort: 50051
          protocol: TCP
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        livenessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50051
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50051
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: csd-socket
          mountPath: /var/run/csd
---
apiVersion: v1
kind: Service
metadata:
  name: instorage-manager
  namespace: instorage-system
  labels:
    app: instorage-manager
spec:
  type: ClusterIP
  clusterIP: None 
  selector:
    app: instorage-manager
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
    protocol: TCP